[project]
name = "ai-engineering"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "instructor>=1.14.5",
    "litellm>=1.81.9",
    "pydantic>=2.12.5",
]
